import './globals.css'
import SearchBar from './components/SearchBar'
import { SearchProvider } from './context/SearchProvider'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="bg-gray-100 text-gray-800">
        <SearchProvider>
          <SearchBar />
          {children}
        </SearchProvider>
      </body>
    </html>
  )
}
