import './globals.css'
import { SearchProvider } from './context/SearchProvider'
import { SummaryProvider } from './context/SummaryProvider'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="bg-gray-100 text-gray-800">
        <SearchProvider>
          <SummaryProvider>
            {children}
          </SummaryProvider>
        </SearchProvider>
      </body>
    </html>
  )
}
